# Generated by Django 3.2.10 on 2021-12-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesUser',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
